ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "dob" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "houseNumber" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "street" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "postalCode" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "emergencyContact" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "emergencyPhone" TEXT;
